language: go # 声明构建语言环境
sudo: false # 开启基于容器的Travis CI任务，让编译效率更高。

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false)
  email:
    recipients:
      - hexileee@gmail.com
  on_success: change
  on_failure: always

go:
  - 1.9

install:
  - go get -u github.com/Masterminds/glide
  - glide install
  - go get github.com/mattn/goveralls

script: # 集成脚本
  - go test -v -cover -coverprofile=rady.coverprofile
  - goveralls -coverprofile=rady.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -race -coverprofile=rady.coverprofile -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

env: #env环境变量设置，travis提供的repo_token安全方式
  global:
    secure: "s967iyBztT7oD7MXfge9IxqEGcNRPT71afW+PbgFsSF/EWr+TBfSWzEPmo0g11uhEE3lMz98n8f/BRZCjbLLEQdyNcroyLN5t6Qz21Qc5tf3Y7E1xiOVjgQnROk39VvJBkf34ZQgIEyXiLe/qReZdQbykUjAjN8y4RPN6/RWBRZOeFEZxT1UW1r/doHBGxsfCLtKGxUVplwlVcEqBfXG1bphMVWbd6P1mGxFvj6YjQNZCm3rbbxPfR0RdKC92+WPaE7lSs735Eo7J/BDU/FLIH+iufQk4BShfNmNOilDi0niljcbvClUGlDchdexUqQaWSDdexDsMa7N0BGwjlRrH9baRKbwVdMDHDxqWSFW8VxzI8K1zTx1pbxCoP+Z8oPdqjoXeReB4hX6U8QLZC5b0YEeI5Q/JDO+ka/uzOJuMKMkYtbk9b28da6SQOgpeafLAs1sde3ik/HfeZkbH+z7NpUgGOYVof5FOta80xg/1WhObNIAnCPXhY30C6WcxRrJcW7NieZb5RQ0rXNbFBQ9lX+hQ5PGtJkMaPXaBsM9ipL4wRDgiEcHPNk3hQ9G1Od2Rv3XLtIGna3y+rY99jIyefuy9jChxhzSWFefTY817fqGXj9T7ntUzVf8qBrvQKEvutj2qKSsbpinX0nmtMAoxiSR5prize+TOe61yzEKL5M="


